# Default values for staticInfra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: nlweb

image:
  controllerImage: neotys/neoload-controller:2023.2.0
  generatorImage: neotys/neoload-loadgenerator:real-browser-2023.2.0
  pullPolicy: Always

neoloadWeb:
  URL: https://neoload-api.nationalgrid.com/
  Token: VZxjp8ucoHzvQonC7qVFerph
  Zone: 6YSKA
  StartReserved: "false"

#Name must be unique for each deployment within the same namespace
controller:
  name: ctrl-for-test-x
  label: my-neoload-controller
  Mode: Managed
  ReplicaCount: 2
  XMX: -Xmx16g
  LivenessProbeFailureThreshold: 3
  LivenessProbeInitialDelaySeconds: 20
  LivenessProbePeriodSeconds: 10
  LivenessProbeSuccessThreshold: 1
  LivenessProbeTimeoutSeconds: 1
  ControllerName: ctrl
  Port: 7400
  Protocol: TCP
  ReadinessProbeFailureThreshold: 3
  ReadinessProbeInitialDelaySeconds: 20
  ReadinessProbePeriodSeconds: 10
  ReadinessProbeSuccessThreshold: 1
  ReadinessProbeTimeoutSeconds: 1
  LimitCPU: 32
  LimitMemory: 64G
  RequestCPU: 10
  RequestMemory: 20G
  TerminationPath: /dev/termination-log
  TerminationPolicy: File
  DNS: ClusterFirst
  RestartPolicy: Always
  SchedulerName: default-scheduler
  TerminationGraceSeconds: 30

generator:
  name: lg-for-test-x
  label: my-neoload-lg
  Mode: Managed
  ReplicaCount: 98
  LGPort: "7100"
  XMX: -Xmx16g
  LivenessProbeFailureThreshold: 3
  LivenessProbeInitialDelaySeconds: 20
  LivenessProbePeriodSeconds: 10
  LivenessProbeSuccessThreshold: 1
  LivenessProbeTimeoutSeconds: 1
  GeneratorName: lg
  Port: 7100
  Protocol: TCP
  ReadinessProbeFailureThreshold: 3
  ReadinessProbeInitialDelaySeconds: 20
  ReadinessProbePeriodSeconds: 10
  ReadinessProbeSuccessThreshold: 1
  ReadinessProbeTimeoutSeconds: 1
  LimitCPU: 32
  LimitMemory: 64G
  RequestCPU: 10
  RequestMemory: 20G
  TerminationPath: /dev/termination-log
  TerminationPolicy: File
  DNS: ClusterFirst
  RestartPolicy: Always
  SchedulerName: default-scheduler
  TerminationGraceSeconds: 30

